###
GET http://localhost:9000/api/usuario/Bruno/A16OCJ/Usuario HTTP/1.1

###
POST http://localhost:9000/api/ingresojugador HTTP/1.1
Content-Type: application/json
{
    "ID": "API95",
    "Dorsal": 95,
    "Usuario": "API",
    "Nombre": "ELAPI",
    "Posicion": "5"
}

###
DELETE http://localhost:9000/api/API99 HTTP/1.1

###
PUT http://localhost:9000/api/usuarioactivo/CASAPI HTTP/1.1
Content-Type: application/json

{
    "Activo": "asd"
}